### ISSUE TITLE
add non scene file compatability

### ISSUE THREAD

**Issue by ianmckenna87** [cixil/godot-scene-palette#1]
it would be more useful for 3d if gltf, glb, fbx etc could be added to the pallette

**Comment by cixil** [comment]
Currently the palette only registers '.tscn' files, which should work for 2d and 3d. Even for 2D projects, if you want to drag and drop an image file into the scene, you'll first have to create a scene for it to be able to see it in the scene palette plugin.

**Comment by ianmckenna87** [comment]
working in 3D means importing 3D files as as a type of "scene", gltf, glb, fbx - but you can't use this with this palette plug-in unless you saved them as a new .tscn.. which is hardly ideal, especially if you have hundreds, or thousands of assets

**Comment by cixil** [comment]
Thanks I will look into adding this when I have time.

**Comment by cixil** [comment]
I'm not familiar with 3d, are there any file types other than gltf, glb, and fbx that should be supported?

**Comment by cixil** [comment]
Ok, I've added support for png, gltf, glb, fbx, and obj files. You can enable support for "non scene" files in the settings panel.

 The editor generates previews for tscn and obj files. Unfortunately, there is no easy way for me to generate a preview for the other 3D file types. But I went ahead and pushed the changes so the option to show 3D file types is still there.

https://github.com/cixil/godot-scene-palette/commit/7176beecc786c77568557a9d17c475c28065e504

**Comment by cixil** [comment]
I added another issue #2 with some information to get started on adding previews for other 3d file types. Since it is out of my scope its not something I plan on working on any time soon.

**Comment by ianmckenna87** [comment]
Good effort, thanks for your work.
